name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      env: 
        SECRET: ${{ secrets.COOL_SECRET }}
    - name: Setup tmate session on dispatch
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled}}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true 
    # - name: Setup tmate session
    #   env:
    #     SECRET: ${{ secrets.COOL_SECRET }}
    #   uses: mxschmitt/action-tmate@v3
    # - name: Setup tmate session 2
    #   uses: mxschmitt/action-tmate@v3
    